#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCity.UserManager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SMDB")]
	public partial class UsersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    #endregion
		
		public UsersDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SMDB"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uID;
		
		private string _uName;
		
		private string _uPwd;
		
		private string _uRealName;
		
		private string _uSex;
		
		private System.Nullable<int> _uAge;
		
		private string _uHobby;
		
		private string _uPhone;
		
		private string _uEmail;
		
		private string _uQQ;
		
		private string _uImage;
		
		private System.Nullable<System.DateTime> _uRegTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuIDChanging(int value);
    partial void OnuIDChanged();
    partial void OnuNameChanging(string value);
    partial void OnuNameChanged();
    partial void OnuPwdChanging(string value);
    partial void OnuPwdChanged();
    partial void OnuRealNameChanging(string value);
    partial void OnuRealNameChanged();
    partial void OnuSexChanging(string value);
    partial void OnuSexChanged();
    partial void OnuAgeChanging(System.Nullable<int> value);
    partial void OnuAgeChanged();
    partial void OnuHobbyChanging(string value);
    partial void OnuHobbyChanged();
    partial void OnuPhoneChanging(string value);
    partial void OnuPhoneChanged();
    partial void OnuEmailChanging(string value);
    partial void OnuEmailChanged();
    partial void OnuQQChanging(string value);
    partial void OnuQQChanged();
    partial void OnuImageChanging(string value);
    partial void OnuImageChanged();
    partial void OnuRegTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnuRegTimeChanged();
    #endregion
		
		public Users()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uID
		{
			get
			{
				return this._uID;
			}
			set
			{
				if ((this._uID != value))
				{
					this.OnuIDChanging(value);
					this.SendPropertyChanging();
					this._uID = value;
					this.SendPropertyChanged("uID");
					this.OnuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string uName
		{
			get
			{
				return this._uName;
			}
			set
			{
				if ((this._uName != value))
				{
					this.OnuNameChanging(value);
					this.SendPropertyChanging();
					this._uName = value;
					this.SendPropertyChanged("uName");
					this.OnuNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uPwd", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string uPwd
		{
			get
			{
				return this._uPwd;
			}
			set
			{
				if ((this._uPwd != value))
				{
					this.OnuPwdChanging(value);
					this.SendPropertyChanging();
					this._uPwd = value;
					this.SendPropertyChanged("uPwd");
					this.OnuPwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uRealName", DbType="VarChar(30)")]
		public string uRealName
		{
			get
			{
				return this._uRealName;
			}
			set
			{
				if ((this._uRealName != value))
				{
					this.OnuRealNameChanging(value);
					this.SendPropertyChanging();
					this._uRealName = value;
					this.SendPropertyChanged("uRealName");
					this.OnuRealNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uSex", DbType="VarChar(2)")]
		public string uSex
		{
			get
			{
				return this._uSex;
			}
			set
			{
				if ((this._uSex != value))
				{
					this.OnuSexChanging(value);
					this.SendPropertyChanging();
					this._uSex = value;
					this.SendPropertyChanged("uSex");
					this.OnuSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uAge", DbType="Int")]
		public System.Nullable<int> uAge
		{
			get
			{
				return this._uAge;
			}
			set
			{
				if ((this._uAge != value))
				{
					this.OnuAgeChanging(value);
					this.SendPropertyChanging();
					this._uAge = value;
					this.SendPropertyChanged("uAge");
					this.OnuAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uHobby", DbType="VarChar(150)")]
		public string uHobby
		{
			get
			{
				return this._uHobby;
			}
			set
			{
				if ((this._uHobby != value))
				{
					this.OnuHobbyChanging(value);
					this.SendPropertyChanging();
					this._uHobby = value;
					this.SendPropertyChanged("uHobby");
					this.OnuHobbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uPhone", DbType="VarChar(20)")]
		public string uPhone
		{
			get
			{
				return this._uPhone;
			}
			set
			{
				if ((this._uPhone != value))
				{
					this.OnuPhoneChanging(value);
					this.SendPropertyChanging();
					this._uPhone = value;
					this.SendPropertyChanged("uPhone");
					this.OnuPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uEmail", DbType="VarChar(50)")]
		public string uEmail
		{
			get
			{
				return this._uEmail;
			}
			set
			{
				if ((this._uEmail != value))
				{
					this.OnuEmailChanging(value);
					this.SendPropertyChanging();
					this._uEmail = value;
					this.SendPropertyChanged("uEmail");
					this.OnuEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uQQ", DbType="VarChar(20)")]
		public string uQQ
		{
			get
			{
				return this._uQQ;
			}
			set
			{
				if ((this._uQQ != value))
				{
					this.OnuQQChanging(value);
					this.SendPropertyChanging();
					this._uQQ = value;
					this.SendPropertyChanged("uQQ");
					this.OnuQQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uImage", DbType="VarChar(100)")]
		public string uImage
		{
			get
			{
				return this._uImage;
			}
			set
			{
				if ((this._uImage != value))
				{
					this.OnuImageChanging(value);
					this.SendPropertyChanging();
					this._uImage = value;
					this.SendPropertyChanged("uImage");
					this.OnuImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uRegTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> uRegTime
		{
			get
			{
				return this._uRegTime;
			}
			set
			{
				if ((this._uRegTime != value))
				{
					this.OnuRegTimeChanging(value);
					this.SendPropertyChanging();
					this._uRegTime = value;
					this.SendPropertyChanged("uRegTime");
					this.OnuRegTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
