<?xml version="1.0" encoding="utf-8"?><Database Name="SMDB" Class="BBSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sql.zhaozhipeng.com;Initial Catalog=SMDB;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SMDB" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="uID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="uPwd" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="uRealName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="uSex" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="uAge" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="uHobby" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="uPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="uEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="uQQ" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="uImage" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="uRegTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Users_BBSNote" Member="BBSNote" ThisKey="uID" OtherKey="uID" Type="BBSNote" />
      <Association Name="Users_BBSAnswer" Member="BBSAnswer" ThisKey="uID" OtherKey="uID" Type="BBSAnswer" />
    </Type>
  </Table>
  <Table Name="dbo.BBSNote" Member="BBSNote">
    <Type Name="BBSNote">
      <Column Name="bnID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bnSubject" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="bnContent" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="bnAddTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="BBSNote_BBSAnswer" Member="BBSAnswer" ThisKey="uID" OtherKey="uID" Type="BBSAnswer" />
      <Association Name="Users_BBSNote" Member="Users" ThisKey="uID" OtherKey="uID" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BBSAnswer" Member="BBSAnswer">
    <Type Name="BBSAnswer">
      <Column Name="baID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bnID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="baContent" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="baAddTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Users_BBSAnswer" Member="Users" ThisKey="uID" OtherKey="uID" Type="Users" IsForeignKey="true" />
      <Association Name="BBSNote_BBSAnswer" Member="BBSNote" ThisKey="uID" OtherKey="uID" Type="BBSNote" IsForeignKey="true" />
    </Type>
  </Table>
</Database>