<?xml version="1.0" encoding="utf-8"?><Database Name="SMDB" Class="GoodsTypeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sql.zhaozhipeng.com;Initial Catalog=SMDB;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SMDB" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GoodsType" Member="GoodsType">
    <Type Name="GoodsType">
      <Column Name="tID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>